\documentclass{article}

% \VignetteIndexEntry{MouseDivGeno Example}

\begin{document}

<<foo,include=FALSE,echo=FALSE>>=
options(keep.source = TRUE, width = 60)
@

\title{MouseDivGeno Example (Version \Sexpr{packageDescription("MouseDivGeno")$Version})}

\author{Hyuna Yang and Keith Sheppard}
\maketitle

\section{Introduction}

This package can be used to

\begin{itemize}
\item genotype MouseDiversity CEL files
\item generate LRR and BAF output from CEL files which is suitable as input for
    the PennCNV program
\item generate CNV calls using our simpleCNV function
\end{itemize}

\section{Genotyping}

First we need to load some data into scope which will give us probe and probeset
level information about the Mouse Diversity Array platform that we are going
to use for genotyping. You can obtain this data from (TODO: add link here)

<<echo=FALSE>>=
setwd("../..")
@

<<>>=
load("MouseDivData.RData")
ls()
@

For the purposes of genotyping we only care about the "snp" data so let's take
a close look at these objects.

\begin{itemize}
\item snpProbeInfo: this data frame contains all of the probe-level information
about snp probes in the mouse diversity platform:
<<>>=
snpProbeInfo[1 : 2, ]
@ 
\item snpInfo: this data frame contains SNP-level information:
<<>>=
snpInfo[1 : 2, ]
@
\item snpReferenceDistribution: a numeric vector which is the reference
distribution used for the quantile normalization of SNP intensities
\end{itemize}

Now we're ready to genotype our CEL files. To do this we will use the
mouseDivGenotype function. By default the mouseDivGenotype function will
run in serial (ie. it will only use a single CPU core), however you can use the
SNOW package in order to run in parallel. The following example will use
the SNOW package to run the genotyping code on two cores:

\section{Generating LRR and BAF for PennCNV}

TODO text here

\section{Simple CNV}

TODO text here

% TODO: include a real bibliography. The following is just an example
%       bibliography

%\begin{thebibliography}{}
%
%\bibitem[Gelman et al.(1996)Gelman, Roberts, and Gilks]{grg}
%Gelman, A., G.~O. Roberts, and W.~R. Gilks (1996).
%\newblock Efficient Metropolis jumping rules.
%\newblock In \emph{Bayesian Statistics, 5 (Alicante, 1994)}, pp.~599--607.
%  Oxford University Press.
%
%\bibitem[Geyer(1992)]{practical}
%Geyer, C.~J. (1992).
%\newblock Practical Markov chain Monte Carlo (with discussion).
%\newblock \emph{Statistical Science}, 7, 473--511.
%
%\bibitem[Geyer and Thompson(1995)]{geyer-temp}
%Geyer, C.~J. and E.~A. Thompson (1995).
%\newblock Annealing Markov chain Monte Carlo with applications to
%    ancestral inference.
%\newblock \emph{Journal of the American Statistical Association}, 90, 909--920.
%
%\end{thebibliography}

\end{document}
